databases:
  - name: django_portfolio_render
    region: singapore
    plan: free
    databaseName: django_portfolio_render
    user: django_user

services:
  - type: web
    name: django_portfolio_render
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_portfolio_render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true